upd

diff --git a/userhome b/userhome
--- a/userhome
+++ b/userhome
@@ -7,8 +7,8 @@ greg_code=0
 is_empty=1
 
 if [ "$1" == "-h" -o "$1" == "--help" -o "$1" == "--usage" -o $# -gt 3 -o "$2" == "-f" -o "$3" == "-f" -o \( $# -gt 1 -a ! "$1" == "-f" \) ]; then
-echo $usage;
-exit 0;
+echo $usage
+exit 0
 fi
 
 if [ ! "$1" == "" ]; then
@@ -21,16 +21,16 @@ login="$3"
 fi
 
 if [ ! -f "$path" ]; then
-echo "file not found" >&2;
-exit 2;
+echo "file not found" >&2
+exit 2
 fi
 
 output=$(grep "^$login:" "$path")
 grep_code=$?
 
 if [ $grep_code -eq 1 ]; then
-echo "user not found" >&2;
-exit 1;
+echo "user not found" >&2
+exit 1
 fi
 
 echo "$output" | cut -d':' -f 6
